/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.LanzarMonedaBack;
import backend.Tablero;

/**
 *
 * @author fer
 */
public class LanzarMoneda extends javax.swing.JFrame {

    /**
     * Creates new form LanzarMoneda
     */
    private String nombreJugador;
    private String iaSeleccionada;

    // Constructor que recibe los nombres del jugador y la IA
    public LanzarMoneda(String nombreJugador, String iaSeleccionada) {
        this.nombreJugador = nombreJugador;
        this.iaSeleccionada = iaSeleccionada;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tira la moneda para ver quién empieza");

        jButton1.setText("Tirar Moneda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Usamos la lógica de lanzar la moneda desde el backend
        boolean jugadorEmpieza = LanzarMonedaBack.lanzar();  // True si empieza el jugador
        String resultado = LanzarMonedaBack.obtenerResultado(jugadorEmpieza);

        // Actualizamos el label con el resultado de la moneda
        jLabel2.setText("Resultado: " + resultado);

        // Abrimos la ventana del tablero, pasando el resultado del lanzamiento
        TableroJuego tablero = new TableroJuego(nombreJugador, iaSeleccionada, jugadorEmpieza);
        tablero.setVisible(true);  // Mostramos el tablero
        this.dispose();  // Cerramos la ventana actual de LanzarMoneda
    }//GEN-LAST:event_jButton1ActionPerformed

    // Evento del botón que se activa cuando el usuario presiona "Tirar Moneda"
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LanzarMoneda("Jugador 1", "IA").setVisible(true);  // Debes pasar los nombres reales aquí
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
