/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Jugador;
import backend.Tablero;
import backend.carta.Carta_I.ICarta;

/**
 *
 * @author fer
 */
public class TableroJuego extends javax.swing.JFrame {

    /**
     * Creates new form TableroJuego
     */
     private Tablero tablero; // Instancia de la lógica del juego
 // Constructor
    public TableroJuego(Tablero tablero) {
        this.tablero = tablero;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblActivoJ1 = new javax.swing.JLabel();
        lblActivoJ2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bancaJ1Area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        bancaJ2Area = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        pilaDescartesJ1Area = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        pilaDescartesJ2Area = new javax.swing.JTextArea();
        btnPremio1J1 = new javax.swing.JButton();
        btnPremio2J1 = new javax.swing.JButton();
        btnPremio3J1 = new javax.swing.JButton();
        btnPremio1J2 = new javax.swing.JButton();
        btnPremio2J2 = new javax.swing.JButton();
        btnPremio3J2 = new javax.swing.JButton();
        lblTiempoJugador = new javax.swing.JLabel();
        lblTiempoReal = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblActivoJ1.setText("Activo Jugador 1: Ninguno");

        lblActivoJ2.setText("Activo Jugador 2: Ninguno");

        bancaJ1Area.setEditable(false);
        bancaJ1Area.setColumns(20);
        bancaJ1Area.setRows(5);
        jScrollPane1.setViewportView(bancaJ1Area);

        bancaJ2Area.setEditable(false);
        bancaJ2Area.setColumns(20);
        bancaJ2Area.setRows(5);
        jScrollPane2.setViewportView(bancaJ2Area);

        pilaDescartesJ1Area.setEditable(false);
        pilaDescartesJ1Area.setColumns(20);
        pilaDescartesJ1Area.setRows(5);
        jScrollPane3.setViewportView(pilaDescartesJ1Area);

        pilaDescartesJ2Area.setColumns(20);
        pilaDescartesJ2Area.setRows(5);
        jScrollPane4.setViewportView(pilaDescartesJ2Area);

        btnPremio1J1.setText("Carta Premio");
        btnPremio1J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio1J1ActionPerformed(evt);
            }
        });

        btnPremio2J1.setText("Carta Premio");
        btnPremio2J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio2J1ActionPerformed(evt);
            }
        });

        btnPremio3J1.setText("Carta Premio");
        btnPremio3J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio3J1ActionPerformed(evt);
            }
        });

        btnPremio1J2.setText("Carta Premio");
        btnPremio1J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio1J2ActionPerformed(evt);
            }
        });

        btnPremio2J2.setText("Carta Premio");
        btnPremio2J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio2J2ActionPerformed(evt);
            }
        });

        btnPremio3J2.setText("Carta Premio");
        btnPremio3J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremio3J2ActionPerformed(evt);
            }
        });

        lblTiempoJugador.setText("\"Tiempo Jugador: 00:00\"");

        lblTiempoReal.setText("\"Tiempo Real: 00:00\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPremio3J1)
                    .addComponent(btnPremio1J1)
                    .addComponent(btnPremio2J1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTiempoJugador)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiempoReal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(lblActivoJ1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblActivoJ2)
                        .addGap(158, 158, 158))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPremio3J2)
                    .addComponent(btnPremio2J2)
                    .addComponent(btnPremio1J2))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActivoJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTiempoJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremio3J2)
                    .addComponent(lblTiempoReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPremio2J2)
                        .addGap(3, 3, 3)
                        .addComponent(btnPremio1J2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblActivoJ2)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPremio3J1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPremio2J1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPremio1J1)
                .addGap(385, 385, 385))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Evento para cuando el jugador 1 selecciona su primera carta premio
  // Método para seleccionar una carta premio
    private void seleccionarPremio(String nombreJugador, int indicePremio) {
        Jugador jugador = obtenerJugadorPorNombre(nombreJugador);  // Método para obtener al jugador

        // Obtener la carta premio correspondiente
        ICarta cartaPremio = tablero.obtenerCartaPremio(jugador, indicePremio);

        // Mostrar información de la carta premio en la interfaz
        if (cartaPremio != null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Carta Premio seleccionada: " + cartaPremio.getNombre());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No hay carta premio disponible.");
        }
    }

    private void btnPremio1J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio1J2ActionPerformed
    seleccionarPremio("Jugador 2", 0);  // Índice 0 para la primera carta premio
    }//GEN-LAST:event_btnPremio1J2ActionPerformed

    private void btnPremio1J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio1J1ActionPerformed
         seleccionarPremio("Jugador 1", 0);  // Índice 0 para la primera carta premio
    }//GEN-LAST:event_btnPremio1J1ActionPerformed

    private void btnPremio2J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio2J1ActionPerformed
     seleccionarPremio("Jugador 1", 1);  // Selecciona la segunda carta premio
    }//GEN-LAST:event_btnPremio2J1ActionPerformed

    private void btnPremio2J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio2J2ActionPerformed
      seleccionarPremio("Jugador 2", 1);  // Selecciona la segunda carta premio
    }//GEN-LAST:event_btnPremio2J2ActionPerformed

    private void btnPremio3J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio3J1ActionPerformed
        seleccionarPremio("Jugador 1", 2);  // Selecciona la tercera carta premio
    }//GEN-LAST:event_btnPremio3J1ActionPerformed

    private void btnPremio3J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremio3J2ActionPerformed
             seleccionarPremio("Jugador 2", 2);  // Selecciona la tercera carta premio
    }//GEN-LAST:event_btnPremio3J2ActionPerformed
public void actualizarCartasActivas(Tablero tablero) {
    if (tablero.getActivoJugador1() != null) {
        lblActivoJ1.setText("Activo Jugador 1: " + tablero.getActivoJugador1().getNombre());
    } else {
        lblActivoJ1.setText("Activo Jugador 1: Ninguno");
    }

    if (tablero.getActivoJugador2() != null) {
        lblActivoJ2.setText("Activo Jugador 2: " + tablero.getActivoJugador2().getNombre());
    } else {
        lblActivoJ2.setText("Activo Jugador 2: Ninguno");
    }
}
public void actualizarBancas(Tablero tablero) {
    bancaJ1Area.setText(tablero.getBancaJugador1().toString());
    bancaJ2Area.setText(tablero.getBancaJugador2().toString());
}
public void actualizarDescartes(Tablero tablero) {
    pilaDescartesJ1Area.setText(tablero.getPilaDescartesJugador1().toString());
    pilaDescartesJ2Area.setText(tablero.getPilaDescartesJugador2().toString());
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bancaJ1Area;
    private javax.swing.JTextArea bancaJ2Area;
    private javax.swing.JButton btnPremio1J1;
    private javax.swing.JButton btnPremio1J2;
    private javax.swing.JButton btnPremio2J1;
    private javax.swing.JButton btnPremio2J2;
    private javax.swing.JButton btnPremio3J1;
    private javax.swing.JButton btnPremio3J2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblActivoJ1;
    private javax.swing.JLabel lblActivoJ2;
    private javax.swing.JLabel lblTiempoJugador;
    private javax.swing.JLabel lblTiempoReal;
    private javax.swing.JTextArea pilaDescartesJ1Area;
    private javax.swing.JTextArea pilaDescartesJ2Area;
    // End of variables declaration//GEN-END:variables
}
